# -*- coding: utf-8 -*-
"""practicedwiththothers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11HleVOfxokhf5fHVyZXK8i_8qZcpcup5

# Snap Growth Analytics Portfolio Project Blueprint

**Project title:** Measuring a Synthetic Snapchat Growth Experiment: Activation, Retention, and Subscription Conversion

**Repository:** `DRIII33/snap-data-science-lv4-`

**Status:** Portfolio design and executable implementation specification. Statistical results are **EXECUTION-DEPENDENT RESULT — MUST BE GENERATED AFTER RUNNING THE PROVIDED CODE**.

> **Project disclaimer:** This is a portfolio project. It is not an official Snap Inc. project, does not use confidential Snap data, and does not claim access to Snap systems, models, metrics, employees, or processes. All generated records are **SYNTHETIC DATA**. Any simulated treatment effect is disclosed as a data-generating assumption. No Snap endorsement is implied.

## 1. Executive Project Overview

This project simulates a product-growth analytics engagement for a hypothetical Snapchat product team. The team wants to know whether a redesigned onboarding and feature-discovery experience improves early activation, day-28 retention, and premium-subscription conversion without harming guardrail metrics.

The project demonstrates the capabilities requested in the Data Scientist, Level 4 job description: SQL and Python analysis, product metrics, data mining, statistical modeling, A/B testing, causal reasoning, dashboards, cross-functional communication, scalable data preparation, data-quality validation, and responsible AI-tool use. It deliberately does **not** claim to demonstrate Snap's internal technology stack or business results.

**Primary decision:** Should the hypothetical product team expand the treatment experience beyond the experiment population?

**Primary estimand:** Intention-to-treat difference in day-28 retention between randomized treatment and control users.

**Secondary estimands:** Activation, subscription conversion, engagement, and guardrail differences.

**Success evidence:** A reproducible data pipeline, validated analytical dataset, pre-specified methodology, confidence intervals and effect sizes, an executive dashboard, and recommendations tied only to executed results.

## 2. Job Description Alignment

| Job-description requirement | Portfolio component | Evidence produced | Tool | Deliverable | Status |
|---|---|---|---|---|---|
| Quantitative analysis and data mining | Cohort, funnel, retention, and experiment analysis | Reproducible metrics and statistical outputs | BigQuery, Python | `sql/06_analysis_views.sql`, notebook | Explicitly demonstrated |
| Statistical modeling | Difference-in-means and regression-adjusted sensitivity analysis | Estimates, CI, diagnostics | Python/statsmodels | `notebooks/03_statistical_analysis.ipynb` | Explicitly demonstrated |
| Core product metrics | Activation, D28 retention, subscription conversion, sessions | Metric definitions and views | BigQuery | `docs/data_dictionary.md` | Explicitly demonstrated |
| A/B testing | Randomized treatment and control assignment | ITT estimate, balance checks, guardrails | Python | Statistical notebook | Explicitly demonstrated |
| Causal methods | Randomized experiment; optional CUPED sensitivity | Treatment, unit, estimand, assumptions | Python | `docs/statistical_methodology.md` | Explicitly demonstrated |
| SQL/big-data querying | Raw-to-analytical transformations | BigQuery-compatible scripts | BigQuery SQL | `sql/` | Explicitly demonstrated |
| Python or R | Generation, validation, analysis | Executable Python | Colab/Python | `src/`, notebooks | Explicitly demonstrated |
| Visuals, dashboards, reports | Looker Studio specification and views | KPI design and wireframes | Looker Studio | `dashboards/` | Explicitly demonstrated |
| Cross-functional collaboration | Stakeholder/RACI and decision memo | Product-facing operating model | Markdown | `docs/stakeholder_operating_model.md` | Supporting evidence |
| Independent project execution | End-to-end dependency plan | Complete reproducibility instructions | Markdown | `README.md` | Supporting evidence |
| Product sense / Snapchat understanding | Snapchat-relevant but clearly hypothetical scenario | Product funnel rationale | Markdown | `docs/business_problem.md` | Supporting evidence |
| AI-tool use with statistical integrity | AI-use protocol and human review checklist | Prompt/output validation record | Markdown | `docs/ai_use_protocol.md` | Supporting evidence |
| Machine learning | Not required for the causal question | No unnecessary model | N/A | `docs/statistical_methodology.md` | Not demonstrated; intentionally excluded |
| Snap internal systems/data | Not available | Explicit limitation | N/A | `Project_Disclaimer.md` | Not demonstrated |

## 3. Business Scenario

**Who:** Hypothetical Snapchat Product Growth, Product Analytics, and Engineering stakeholders. The scenario is inferred from the job description's explicit collaboration with product managers, engineers, product marketers, and designers; it is not a claim about Snap's actual team structure.

**What:** A redesigned onboarding and feature-discovery flow is randomly assigned to eligible new users. The product team needs evidence about activation, retention, premium conversion, and user-experience guardrails.

**Why:** A higher early-value experience could improve durable engagement and monetization, but optimizing one short-term metric could reduce quality or create misleading gains. A Level 4 data scientist would define metrics, validate data, analyze the experiment, and convert results into a launch recommendation.

**Where:** Hypothetical Snapchat mobile onboarding and early product-discovery funnel.

**When:** Configurable synthetic observation window; default 90 days beginning `2026-01-01`.

**Business outcome:** Make a launch/iterate/stop decision using retention and activation as primary outcomes, subscription conversion as a secondary outcome, and notification opt-outs, reports, and session-quality proxies as guardrails.

## 4. Business Problem and Analytical Questions

**Primary problem:** Determine whether the hypothetical onboarding treatment causally improves durable user value enough to justify expansion.

**Secondary problems:**
1. Early activation may not translate into durable retention.
2. Subscription conversion may differ by treatment while being underpowered.
3. Aggregate results may hide heterogeneous effects by market, device, or acquisition channel.
4. Event data may contain duplicates, missingness, impossible timestamps, and leakage risks.
5. A dashboard could make an invalid experiment appear decision-ready.

**Questions:**
1. Does treatment change activation within seven days?
2. Does treatment change day-28 retention?
3. Does treatment change subscription conversion within 28 days?
4. Does treatment change sessions, messages, or AR-feature discovery?
5. Are guardrails materially worse?
6. Are effects consistent across pre-treatment segments?
7. Are the conclusions sensitive to covariate adjustment and missing-data handling?
8. What data-quality or measurement issues limit the decision?

## 5. Hypotheses and Estimands

| ID | Null | Alternative | Metric/population | Unit | Method | Alpha/effect/CI | Interpretation |
|---|---|---|---|---|---|---|---|
| H1 | Treatment and control have equal D28 retention | Treatment changes D28 retention | Randomized eligible new users | User | Difference in proportions; logistic regression sensitivity | Two-sided alpha .05; risk difference and ratio; bootstrap or Wilson CI | Expansion requires positive practical effect and no material guardrail harm |
| H2 | Equal seven-day activation | Treatment changes activation | Same | User | Difference in proportions | Alpha .05; risk difference and CI | Secondary evidence of early product value |
| H3 | Equal 28-day subscription conversion | Treatment changes conversion | Same | User | Difference in proportions; Fisher/exact sensitivity for sparse cells | Alpha .05; risk difference and CI | Do not claim revenue impact without price/eligibility data |
| H4 | Equal notification opt-out/report guardrails | Treatment changes guardrails | Same | User | Difference in proportions | Alpha .05; CI; practical threshold pre-specified | Any harmful direction triggers investigation |

**Practical thresholds (ASSUMPTION):** Define before execution, for example: at least +1 percentage point D28 retention, no guardrail decline worse than -0.5 points, and a confidence interval that is decision-compatible. These thresholds are not Snap standards.

## 6. Data Strategy and Synthetic Data-Generating Process

Synthetic data is selected because internal Snapchat event data is unavailable, privacy-sensitive, and not reproducible by a portfolio reviewer. No public dataset is required because a public dataset would not provide randomized onboarding exposure, user-level event history, and subscription outcomes in one coherent structure.

### Entities and grains

- `users`: one row per synthetic user; primary key `user_id`.
- `experiment_assignments`: one row per user assignment; `user_id` foreign key.
- `events`: one row per product event; unique `event_id`; foreign key `user_id`.
- `subscriptions`: zero or one row per user for the simulated observation period.
- `daily_user_features`: one row per user-day, generated after event aggregation.

### Simulated relationships

The generator creates plausible associations among acquisition channel, market, device, latent propensity, treatment, activation, retention, engagement, and subscription. Treatment is assigned by a deterministic seeded randomization independent of pre-treatment variables. The generator may include a documented treatment effect for pipeline validation, but the expected recovered effect is not reported until code is run.

**Known limitation:** Because the data-generating process is simulated, recovery of an embedded effect validates implementation rather than proving a real product effect.

### Missingness, noise, and outliers

- Small configurable missingness in optional device/channel fields.
- Duplicate-event injection is optional for validation testing and must be removed or flagged.
- Heavy-tailed session/message counts.
- Timestamp boundary cases.
- No outcome is constructed from post-treatment variables used as predictors.

## 7. BigQuery Architecture

**Project ID:** `driiiportfolio`  
**Datasets:** `snap_growth_raw`, `snap_growth_transform`, `snap_growth_analytics`, `snap_growth_dashboard`

| Dataset | Table/view | Grain | Key columns | Partition/cluster |
|---|---|---|---|---|
| raw | `users` | user | `user_id` | cluster `market, device_type` |
| raw | `experiment_assignments` | user assignment | `user_id` | cluster `treatment_group` |
| raw | `events` | event | `event_id` | partition `event_date`; cluster `user_id, event_name` |
| raw | `subscriptions` | user subscription | `user_id` | partition `subscription_date` |
| transform | `clean_events` | valid event | `event_id` | partition `event_date`; cluster `user_id, event_name` |
| analytics | `user_experiment_metrics` | user | `user_id` | cluster `treatment_group, market` |
| analytics | `experiment_results` | metric/segment | `metric_name, segment_name, segment_value` | none |
| dashboard | `kpi_daily` | date/treatment | `metric_date, treatment_group` | partition `metric_date` |
| dashboard | `executive_summary` | one result/metric | `metric_name` | none |
| dashboard | `data_quality_summary` | check | `check_name` | none |

**Expected default size (ASSUMPTION):** 50,000 users and approximately 1–3 million events, configurable downward for Colab. Exact counts are execution-dependent.

### Schema summary

| Table | Column | Type | Description | Key | Nullable | Source |
|---|---|---|---|---|---|---|
| users | user_id | STRING | Synthetic user ID | PK | no | generator |
| users | signup_date | DATE | Eligibility date |  | no | generator |
| users | market | STRING | Synthetic market group |  | no | generator |
| users | device_type | STRING | Device category |  | no | generator |
| users | acquisition_channel | STRING | Acquisition source |  | yes | generator |
| experiment_assignments | user_id | STRING | Assigned user | PK/FK | no | generator |
| experiment_assignments | treatment_group | STRING | control/treatment |  | no | generator |
| experiment_assignments | assignment_ts | TIMESTAMP | Assignment time |  | no | generator |
| events | event_id | STRING | Event ID | PK | no | generator |
| events | user_id | STRING | Event owner | FK | no | generator |
| events | event_ts | TIMESTAMP | Event timestamp |  | no | generator |
| events | event_name | STRING | Event type |  | no | generator |
| events | session_id | STRING | Session identifier |  | yes | generator |
| subscriptions | user_id | STRING | Subscriber | PK/FK | no | generator |
| subscriptions | subscription_date | DATE | Conversion date |  | no | generator |
| subscriptions | plan | STRING | Synthetic plan |  | no | generator |

## 8. Repository Design

**Recommended repository name:** `snap-growth-experiment-analytics`  
**Description:** `Synthetic end-to-end product-growth experiment analytics project aligned to Snap Data Scientist Level 4 skills.`

```text
snap-growth-experiment-analytics/
├── README.md
├── Executive_Summary.md
├── Dashboard_Executive_Summary.md
├── Project_Disclaimer.md
├── LICENSE
├── .gitignore
├── requirements.txt
├── docs/
│   ├── business_problem.md
│   ├── data_dictionary.md
│   ├── data_architecture.md
│   ├── data_flow.md
│   ├── job_description_alignment.md
│   ├── statistical_methodology.md
│   ├── stakeholder_operating_model.md
│   ├── ai_use_protocol.md
│   └── limitations.md
├── data/README.md
├── sql/
│   ├── 01_create_datasets.sql
│   ├── 02_create_raw_tables.sql
│   ├── 03_data_quality_checks.sql
│   ├── 04_transform.sql
│   ├── 05_feature_engineering.sql
│   ├── 06_analysis_views.sql
│   ├── 07_dashboard_views.sql
│   └── 08_final_validation.sql
├── notebooks/
│   ├── 01_data_generation.ipynb
│   ├── 02_data_validation.ipynb
│   └── 03_statistical_analysis.ipynb
├── src/
│   ├── data_generation/generate_synthetic_data.py
│   ├── validation/validate_data.py
│   └── analysis/experiment_analysis.py
├── dashboards/
│   ├── README.md
│   └── dashboard_specification.md
├── outputs/
│   ├── figures/.gitkeep
│   └── reports/.gitkeep
└── tests/data_quality_tests.md
```

## 9. Reproducible Python Generator

Save the following as `src/data_generation/generate_synthetic_data.py`. It is intentionally modest enough for Colab free resources; increase configuration only after profiling.

```python
from pathlib import Path
import numpy as np
import pandas as pd

SEED = 20260922
N_USERS = 50_000
START = pd.Timestamp("2026-01-01", tz="UTC")
OUT = Path("data/synthetic")
rng = np.random.default_rng(SEED)
OUT.mkdir(parents=True, exist_ok=True)

markets = np.array(["north_america", "europe", "rest_of_world"])
devices = np.array(["ios", "android", "web"])
channels = np.array(["organic", "paid_social", "referral", "search"])
users = pd.DataFrame({
    "user_id": [f"u_{i:07d}" for i in range(N_USERS)],
    "signup_date": (START + pd.to_timedelta(rng.integers(0, 60, N_USERS), unit="D")).date,
    "market": rng.choice(markets, N_USERS, p=[.35, .30, .35]),
    "device_type": rng.choice(devices, N_USERS, p=[.48, .48, .04]),
    "acquisition_channel": rng.choice(channels, N_USERS, p=[.55, .20, .15, .10]),
    "latent_propensity": np.clip(rng.normal(0, 1, N_USERS), -3, 3)
})

assign = pd.DataFrame({
    "user_id": users.user_id,
    "treatment_group": rng.choice(["control", "treatment"], N_USERS),
    "assignment_ts": pd.to_datetime(users.signup_date, utc=True) + pd.to_timedelta(rng.integers(0, 86_400, N_USERS), unit="s")
})

# SIMULATED DATA-GENERATING ASSUMPTION: treatment modestly increases activation.
base_activation = 1 / (1 + np.exp(-(0.2 + .55 * users.latent_propensity)))
treatment_lift = np.where(assign.treatment_group.eq("treatment"), 0.08, 0.0)
activated = rng.random(N_USERS) < np.clip(base_activation + treatment_lift, .01, .99)

n_events = int(N_USERS * 28)
user_idx = rng.integers(0, N_USERS, n_events)
events = pd.DataFrame({
    "event_id": [f"e_{i:09d}" for i in range(n_events)],
    "user_id": users.user_id.to_numpy()[user_idx],
    "event_ts": START + pd.to_timedelta(rng.integers(0, 90 * 86_400, n_events), unit="s"),
    "event_name": rng.choice(["app_open", "message_sent", "story_view", "lens_used", "feature_discovered"], n_events, p=[.40, .18, .22, .12, .08]),
    "session_id": [f"s_{i:010d}" for i in range(n_events)]
})

# Ensure activated users have at least one discovery event; this is simulated product logic.
activated_ids = users.loc[activated, "user_id"].to_numpy()
extra = pd.DataFrame({
    "event_id": [f"e_extra_{i:08d}" for i in range(len(activated_ids))],
    "user_id": activated_ids,
    "event_ts": START + pd.to_timedelta(rng.integers(0, 7 * 86_400, len(activated_ids)), unit="s"),
    "event_name": "feature_discovered",
    "session_id": [f"s_extra_{i:08d}" for i in range(len(activated_ids))]
})
events = pd.concat([events, extra], ignore_index=True)

# Retention is simulated from activation and latent propensity, not calculated from post-treatment events.
user_frame = users.merge(assign, on="user_id")
retention_p = 1 / (1 + np.exp(-(-1.0 + .9 * user_frame.latent_propensity + .9 * activated + .10 * user_frame.treatment_group.eq("treatment"))))
retained = rng.random(N_USERS) < retention_p
subscription_p = 1 / (1 + np.exp(-(-3.2 + .5 * user_frame.latent_propensity + .25 * activated + .08 * user_frame.treatment_group.eq("treatment"))))
subscriber = rng.random(N_USERS) < subscription_p
subscriptions = user_frame.loc[subscriber, ["user_id"]].copy()
subscriptions["subscription_date"] = pd.to_datetime(user_frame.loc[subscriber, "signup_date"], utc=True) + pd.to_timedelta(rng.integers(1, 29, len(subscriptions)), unit="D")
subscriptions["plan"] = rng.choice(["plus", "lens_plus"], len(subscriptions), p=[.75, .25])

# Persist latent labels only for validation/reproducibility; exclude from analytical features.
users["simulated_activation_label"] = activated
users["simulated_d28_retained_label"] = retained

for name, frame in [("users", users), ("experiment_assignments", assign), ("events", events), ("subscriptions", subscriptions)]:
    frame.to_csv(OUT / f"{name}.csv", index=False)

assert users.user_id.is_unique
assert assign.user_id.is_unique
assert events.event_id.is_unique
assert set(assign.user_id).issubset(set(users.user_id))
assert set(events.user_id).issubset(set(users.user_id))
assert set(subscriptions.user_id).issubset(set(users.user_id))
assert set(assign.treatment_group).issubset({"control", "treatment"})
assert events.event_ts.notna().all()
print({"users": len(users), "assignments": len(assign), "events": len(events), "subscriptions": len(subscriptions)})
print(users.isna().sum())
```

**Expected resource profile:** execution-dependent; the default is designed to fit ordinary Colab memory more comfortably than a massive event simulation. Measure actual RAM, runtime, and CSV sizes after execution; do not claim them in advance.

## 10. Data Validation Framework

Required checks: completeness, uniqueness, referential integrity, allowed categories, date bounds, duplicate events, event-to-user joins, treatment balance, leakage, outliers, and distribution anomalies.

Example Python checks:

```python
def quality_report(users, assign, events, subscriptions):
    checks = []
    def add(name, expected, actual, status, remediation="None"):
        checks.append({"check": name, "expected": expected, "actual": actual, "status": status, "remediation": remediation})
    add("user_pk_unique", "0 duplicates", int(users.user_id.duplicated().sum()), "PASS" if users.user_id.is_unique else "FAIL")
    add("assignment_fk", "all users exist", int((~assign.user_id.isin(users.user_id)).sum()), "PASS" if assign.user_id.isin(users.user_id).all() else "FAIL")
    add("event_fk", "all users exist", int((~events.user_id.isin(users.user_id)).sum()), "PASS" if events.user_id.isin(users.user_id).all() else "FAIL")
    add("event_pk_unique", "0 duplicates", int(events.event_id.duplicated().sum()), "PASS" if events.event_id.is_unique else "FAIL")
    add("allowed_treatment", "control/treatment", sorted(assign.treatment_group.unique().tolist()), "PASS" if set(assign.treatment_group) <= {"control", "treatment"} else "FAIL")
    add("null_user_ids", "0", int(users.user_id.isna().sum()), "PASS" if users.user_id.notna().all() else "FAIL")
    return pd.DataFrame(checks)
```

**Data Quality Report:** The `actual` and `status` fields must be populated by execution. Do not write “clean” before running these checks. Expected status is `PASS` for intentionally valid generated data; injected defects must produce `FAIL` and be documented as remediation tests.

## 11. BigQuery SQL Plan

Use explicit schemas rather than relying only on autodetection. CSV loading is supported through the BigQuery console, `bq`, or client libraries; see [Google's dataset documentation](https://docs.cloud.google.com/bigquery/docs/datasets) and [CSV loading documentation](https://docs.cloud.google.com/bigquery/docs/loading-data-cloud-storage-csv).

### `sql/01_create_datasets.sql`

```sql
CREATE SCHEMA IF NOT EXISTS `driiiportfolio.snap_growth_raw` OPTIONS(location='US');
CREATE SCHEMA IF NOT EXISTS `driiiportfolio.snap_growth_transform` OPTIONS(location='US');
CREATE SCHEMA IF NOT EXISTS `driiiportfolio.snap_growth_analytics` OPTIONS(location='US');
CREATE SCHEMA IF NOT EXISTS `driiiportfolio.snap_growth_dashboard` OPTIONS(location='US');
```

### `sql/02_create_raw_tables.sql`

Create raw tables with the schema in Section 7. Partition `events` by `DATE(event_ts)` and cluster by `user_id, event_name`. For reproducibility, the repository should include the exact `CREATE TABLE` statements generated from the loaded CSV schema; never use `SELECT *` in analytical SQL.

### `sql/03_data_quality_checks.sql`

```sql
SELECT 'duplicate_event_id' AS check_name, COUNT(*) AS failures
FROM (
  SELECT event_id FROM `driiiportfolio.snap_growth_raw.events`
  GROUP BY event_id HAVING COUNT(*) > 1
)
UNION ALL
SELECT 'orphan_event_user', COUNT(*)
FROM `driiiportfolio.snap_growth_raw.events` e
LEFT JOIN `driiiportfolio.snap_growth_raw.users` u USING (user_id)
WHERE u.user_id IS NULL
UNION ALL
SELECT 'invalid_treatment', COUNT(*)
FROM `driiiportfolio.snap_growth_raw.experiment_assignments`
WHERE treatment_group NOT IN ('control', 'treatment');
```

### `sql/04_transform.sql`

```sql
CREATE OR REPLACE TABLE `driiiportfolio.snap_growth_transform.clean_events`
PARTITION BY event_date CLUSTER BY user_id, event_name AS
SELECT DISTINCT
  event_id, user_id, DATE(event_ts) AS event_date, event_ts,
  LOWER(TRIM(event_name)) AS event_name, session_id
FROM `driiiportfolio.snap_growth_raw.events`
WHERE event_id IS NOT NULL AND user_id IS NOT NULL
  AND event_ts IS NOT NULL
  AND event_name IN ('app_open','message_sent','story_view','lens_used','feature_discovered');
```

### `sql/05_feature_engineering.sql`

```sql
CREATE OR REPLACE TABLE `driiiportfolio.snap_growth_analytics.user_experiment_metrics`
CLUSTER BY treatment_group, market AS
WITH base AS (
  SELECT u.user_id, u.signup_date, u.market, u.device_type,
         u.acquisition_channel, a.treatment_group, a.assignment_ts
  FROM `driiiportfolio.snap_growth_raw.users` u
  JOIN `driiiportfolio.snap_growth_raw.experiment_assignments` a USING (user_id)
), agg AS (
  SELECT b.user_id,
    COUNTIF(e.event_name = 'app_open' AND e.event_date BETWEEN b.signup_date AND DATE_ADD(b.signup_date, INTERVAL 6 DAY)) > 0 AS activated,
    COUNTIF(e.event_date BETWEEN b.signup_date AND DATE_ADD(b.signup_date, INTERVAL 27 DAY)) > 0 AS d28_retained,
    COUNTIF(e.event_name = 'feature_discovered' AND e.event_date BETWEEN b.signup_date AND DATE_ADD(b.signup_date, INTERVAL 6 DAY)) > 0 AS discovered_feature,
    COUNTIF(e.event_name = 'message_sent' AND e.event_date BETWEEN b.signup_date AND DATE_ADD(b.signup_date, INTERVAL 27 DAY)) AS messages_28d,
    COUNTIF(e.event_name = 'app_open' AND e.event_date BETWEEN b.signup_date AND DATE_ADD(b.signup_date, INTERVAL 27 DAY)) AS opens_28d
  FROM base b LEFT JOIN `driiiportfolio.snap_growth_transform.clean_events` e USING (user_id)
  GROUP BY b.user_id
)
SELECT b.*, a.* EXCEPT(user_id),
  EXISTS(SELECT 1 FROM `driiiportfolio.snap_growth_raw.subscriptions` s
         WHERE s.user_id=b.user_id AND s.subscription_date BETWEEN b.signup_date AND DATE_ADD(b.signup_date, INTERVAL 27 DAY)) AS subscribed_28d
FROM base b JOIN agg a USING (user_id);
```

### `sql/06_analysis_views.sql`

Create a view grouped by treatment and optional pre-treatment segments containing users, activation rate, D28 retention rate, subscription conversion, means, and guardrails. Use denominators based on users, not events.

### `sql/07_dashboard_views.sql`

Create:
- `kpi_daily`: daily eligible-user counts and treatment rates.
- `executive_summary`: treatment/control metric estimates and execution-populated CI/p-values.
- `data_quality_summary`: check name, expected, actual, status, remediation.

### `sql/08_final_validation.sql`

Validate one row per user in `user_experiment_metrics`, no orphan keys, no post-treatment feature in pre-treatment adjustment set, and no join multiplication. Any failed check blocks publication.

## 12. Statistical Methodology

The primary analysis is an intention-to-treat randomized comparison because treatment assignment is the causal intervention. The primary result should be a risk difference with a 95% confidence interval. A logistic regression may be used as a pre-specified sensitivity analysis with only pre-treatment covariates. Bootstrap intervals may be used for skewed count outcomes.

**Why not automatically use ML?** The core decision is causal and the synthetic sample is structured for interpretable experiment measurement. A predictive model is not necessary. Adding ML would risk distracting from the business question and introducing leakage. A future extension could predict subscription propensity only if a separate decision requires targeting and if temporal validation is implemented.

**Assumptions/diagnostics:** randomization, assignment integrity, no material interference, correct outcome windows, independent user-level units, adequate sample size, no sample-ratio mismatch, pre-treatment covariate balance, and reliable event instrumentation. Inspect balance tables, treatment proportions, outcome counts, missingness, distributions, and sensitivity to regression adjustment.

**Multiple testing:** D28 retention is primary. Secondary metrics are labeled exploratory or adjusted using a documented method. Do not select the most favorable metric after execution.

## 13. Statistical Notebook Structure

`notebooks/03_statistical_analysis.ipynb` must contain:

1. `01_Project_Setup`: versions, seed, paths, alpha, practical thresholds.
2. `02_Load_Data`: load the analytical extract only.
3. `03_Data_Validation`: grain, assignment, missingness, duplicate and join checks.
4. `04_Exploratory_Data_Analysis`: cohort, treatment balance, distributions.
5. `05_Feature_Engineering`: pre-treatment features and outcomes; leakage review.
6. `06_Methodology`: estimand, hypotheses, test selection.
7. `07_Assumption_Checks`: balance, SRM, sample size, outcome windows.
8. `08_Statistical_Analysis`: ITT estimates, optional regression sensitivity.
9. `09_Effect_Size`: risk difference, relative risk, standardized count effects.
10. `10_Confidence_Intervals`: 95% intervals and practical thresholds.
11. `11_Sensitivity_Analysis`: regression adjustment, exclusions, missingness.
12. `12_Visualization`: confidence-interval plots, funnel/retention charts.
13. `13_Insights`: descriptive, diagnostic, statistical, business findings.
14. `14_Business_Recommendations`: only after results exist.
15. `15_Final_Validation`: checklist and export of result tables.

Every result cell must label numerical outputs **EXECUTION-DEPENDENT RESULT — MUST BE GENERATED AFTER RUNNING THE PROVIDED CODE** until the notebook has actually run.

## 14. Understanding the Data Flow: From Synthetic Data to Statistical Insights

**Synthetic/Public Source Data** → Python/Colab generates relational user, assignment, event, and subscription records.  
**Python / Google Colab** → deterministic generation and local validation.  
**CSV Files** → portable raw artifacts; not committed if large or containing generated data by default.  
**BigQuery Raw Layer** → explicit-schema ingestion and low-cost scalable storage.  
**Data Quality Validation** → key, category, timestamp, range, and referential checks.  
**BigQuery Transformation Layer** → standardization, deduplication, valid-event filtering.  
**Feature Engineering** → user-level pre-treatment covariates and fixed-window outcomes.  
**Analytical Dataset / Views** → one row per user for statistical analysis.  
**Google Colab Statistical Analysis** → experiment estimates, diagnostics, uncertainty, and sensitivity.  
**Statistical Results** → persisted CSV/Parquet/BigQuery result artifacts.  
**Business Insights** → evidence, interpretation, recommendation, limitation.  
**BigQuery Dashboard Views** → clean KPI and methodology views.  
**Looker Studio** → executive-facing charts and filters.  
**Executive Decision Support** → launch, iterate, or stop decision with documented uncertainty.

## 15. Looker Studio Dashboard Specification

**Dashboard title:** `Synthetic Snapchat Growth Experiment — Executive Decision Support`

### Page 1 — Executive Decision
- Audience: product and business leadership.
- Source: `executive_summary`.
- KPIs: eligible users, treatment share, activation, D28 retention, subscription conversion, guardrail status.
- Charts: KPI cards; treatment/control dot-and-interval chart; decision banner; methodology note.
- Filters: date/cohort, market, device, acquisition channel.
- Question: Is the treatment decision-ready?

### Page 2 — Funnel and Retention
- Source: `user_experiment_metrics` or an aggregated view.
- Charts: activation funnel, retention by treatment, cohort trend.
- Question: Where does treatment change user behavior?

### Page 3 — Segments and Guardrails
- Source: `segment_results` and `guardrail_results`.
- Charts: segment forest plot/table, opt-out/report rates, sample sizes.
- Question: Is the result consistent and safe across important pre-treatment groups?

### Page 4 — Data Quality and Methodology
- Source: `data_quality_summary` and `experiment_metadata`.
- Charts: pass/fail table, data freshness, metric definitions, experiment assumptions.
- Question: Can stakeholders trust the analysis?

**Wireframe:** header → decision banner → primary KPI cards → CI chart → funnel/retention visuals → segment and guardrail table → methodology and limitations panel.

### Component mapping

| Component | BigQuery view | Dimension | Metric | Calculation | Question |
|---|---|---|---|---|---|
| Retention card | `executive_summary` | treatment | D28 retention | retained/users | Did retention change? |
| Funnel | `funnel_summary` | treatment, stage | users | distinct users by stage | Where is lift? |
| Segment chart | `segment_results` | market/device/channel | risk difference, CI | treatment-control | Is effect heterogeneous? |
| Quality table | `data_quality_summary` | check | failures/status | validation output | Is data trustworthy? |

Use BigQuery views rather than raw tables. Document refresh policy, owner, source lineage, metric definitions, and limitations in the dashboard itself.

## 16. Reproduction Instructions

1. Confirm access to Google Cloud project `driiiportfolio` or create/use a permitted project; enable BigQuery.
2. Create datasets with `sql/01_create_datasets.sql` in a chosen location.
3. Open Colab, install pinned packages from `requirements.txt`, and run the generator.
4. Run Python validation and save the data-quality report.
5. Upload CSV files through the BigQuery console or Cloud Storage; specify schema and skip the header row. Follow [official CSV loading guidance](https://docs.cloud.google.com/bigquery/docs/loading-data-cloud-storage-csv).
6. Execute SQL scripts in order 02 through 08.
7. Export the analytical view to Colab or query it with the BigQuery client.
8. Run the statistical notebook from a fresh runtime.
9. Persist result tables and figures under `outputs/`.
10. Connect Looker Studio's native BigQuery connector to dashboard views.
11. Add dashboard notes for refresh, ownership, source lineage, and synthetic-data limitations.
12. Run the final QA checklist and reproduce from scratch.

**Dependencies:** Python 3.x, `numpy`, `pandas`, `scipy`, `statsmodels`, `matplotlib`, `seaborn`, `google-cloud-bigquery`, and `pyarrow` as needed. Pin tested versions after execution; do not claim a version has been tested until it has been run.

## 17. BigQuery and Colab Cost Controls

Current pricing, quotas, and free-tier terms can change. Verify before execution using official [BigQuery pricing](https://cloud.google.com/bigquery/pricing), [cost controls](https://docs.cloud.google.com/bigquery/docs/best-practices-costs), and [quotas](https://cloud.google.com/bigquery/quotas). Do not treat third-party summaries as authoritative.

Checklist:
- Use small synthetic data by default.
- Avoid `SELECT *`.
- Partition events and filter partition columns.
- Cluster by common join/filter fields.
- Use dry runs or query byte estimates before expensive queries.
- Set maximum bytes billed where appropriate.
- Prefer materialized analytical views/tables for repeated dashboard work.
- Retrieve only the user-level analytical subset into Colab.
- Delete or expire temporary tables.
- Monitor billing and quota dashboards.
- Do not assume free-tier amounts or Colab runtime limits; verify at execution time.

Colab's official FAQ states that resources and availability are dynamic and not guaranteed; this project intentionally avoids GPU dependence and large model training. [Colab FAQ](https://research.google.com/colaboratory/faq.html)

## 18. Insights, Recommendations, and Limitations

### Findings

Before execution: **EXPECTED OUTPUT — MUST BE GENERATED AFTER EXECUTION**. The repository must separate:
- Descriptive: what happened in the generated sample.
- Diagnostic: plausible mechanisms, labeled **INTERPRETATION**.
- Statistical: estimates, CI, p-values, and effect sizes from executed code.
- Business: decision implications, with assumptions.

### Recommendation template

| Evidence | Recommendation | Rationale | Expected impact | Measurement | Risk |
|---|---|---|---|---|---|
| EXECUTION-DEPENDENT RESULT | Expand, iterate, or stop | Tied to primary estimand and guardrails | Formula only; no invented dollars | Follow-up experiment/monitoring | Generalization, novelty, instrumentation |

### Limitations

- All user and event data are synthetic.
- Simulated treatment effects are not real Snap effects.
- The generator cannot reproduce Snap's user behavior, scale, privacy controls, economics, or infrastructure.
- Synthetic distributions and missingness assumptions may be wrong.
- Randomization removes confounding only in the simulated experiment; it does not establish external validity.
- The observation window may be too short for durable retention.
- No real ad revenue, pricing, costs, or lifetime value are included.
- Segment analysis can be underpowered and exploratory.
- Event definitions are portfolio abstractions.
- Dashboard results are illustrative until executed.

## 19. AI Use Protocol

AI may assist with drafting SQL, explaining errors, generating test cases, or suggesting visualizations. The analyst remains responsible for:

1. Reviewing every generated query.
2. Running key queries independently.
3. Checking join grain and denominator logic.
4. Verifying statistical formulas against authoritative references.
5. Preventing leakage and fabricated results.
6. Documenting material AI assistance without entering confidential data.

## 20. End-to-End Execution Order

| Step | Objective | Tool/output | Validation | Dependency/completion |
|---|---|---|---|---|
| 01 | Review job description | Requirements matrix | Every requirement classified | None; matrix complete |
| 02 | Define scenario | Business problem doc | Measurable decision exists | 01 |
| 03 | Define estimands | Hypothesis table | Primary metric pre-specified | 02 |
| 04 | Design schema | Architecture/data dictionary | Grain/keys documented | 03 |
| 05 | Generate data | CSVs | Seed, ranges, keys pass | 04 |
| 06 | Validate locally | Quality report | No unexplained failures | 05 |
| 07 | Create BigQuery resources | Datasets/tables | Correct location/schema | 06 |
| 08 | Load raw data | Raw tables | Row counts and schema | 07 |
| 09 | Run DQ SQL | Check results | Failures remediated | 08 |
| 10 | Transform | Clean events | No invalid events | 09 |
| 11 | Engineer features | User analytical table | One row/user, no leakage | 10 |
| 12 | Analyze | Statistical outputs | Assumptions/CI/effects | 11 |
| 13 | Sensitivity test | Robustness outputs | Differences explained | 12 |
| 14 | Create dashboard views | Clean views | Metric lineage documented | 12 |
| 15 | Build dashboard | Looker Studio report | Filters and sources work | 14 |
| 16 | Write findings | Reports | No fabricated numbers | 12,15 |
| 17 | Final QA | Checklist | All critical checks pass | 16 |
| 18 | Fresh reproduction | Re-run project | Independent reproduction succeeds | 17 |

## 21. Final QA Audit

- [ ] Scenario is explicitly hypothetical and aligned to the job description.
- [ ] No Snap confidential data or internal systems are implied.
- [ ] Synthetic data is labeled everywhere.
- [ ] Primary estimand and metric were defined before analysis.
- [ ] Every table has documented grain and keys.
- [ ] SQL is BigQuery-compatible and avoids unnecessary scans.
- [ ] Python has imports, seed, validation, and output paths.
- [ ] Data-quality checks include completeness, uniqueness, validity, consistency, timeliness, outliers, and leakage.
- [ ] Joins are tested for multiplication.
- [ ] Treatment assignment and sample-ratio checks are run.
- [ ] No post-treatment variables enter adjustment features.
- [ ] Confidence intervals, effect sizes, and practical thresholds are reported.
- [ ] Statistical and business significance are separated.
- [ ] No result is stated before execution.
- [ ] Dashboard uses curated views, not raw tables.
- [ ] Dashboard documents source, refresh, owner, definitions, and limitations.
- [ ] BigQuery pricing and quotas are verified from official documentation at execution time.
- [ ] Colab resources are not assumed to be guaranteed.
- [ ] Repository reproduces from a fresh environment.

## 22. Deliverable Manifest

| Deliverable | File/location | Purpose | Generated by | Status |
|---|---|---|---|---|
| Project blueprint | `docs/portfolio_project_blueprint.md` | Complete design and execution specification | Markdown | This file |
| README | `README.md` | Public project orientation and reproduction | Markdown | To create |
| Executive summary | `Executive_Summary.md` | C-suite narrative after execution | Markdown | Template required |
| Dashboard summary | `Dashboard_Executive_Summary.md` | Dashboard use and interpretation | Markdown | Template required |
| Disclaimer | `Project_Disclaimer.md` | Non-affiliation and synthetic-data disclosure | Markdown | Required |
| Business problem | `docs/business_problem.md` | Scenario and analytical questions | Markdown | Required |
| Data dictionary | `docs/data_dictionary.md` | Schemas, grains, keys, definitions | Markdown | Required |
| Architecture | `docs/data_architecture.md` | BigQuery layers and lineage | Markdown/SQL | Required |
| Data flow | `docs/data_flow.md` | End-to-end flow | Markdown | Required |
| Methodology | `docs/statistical_methodology.md` | Estimands, tests, assumptions | Markdown | Required |
| Alignment matrix | `docs/job_description_alignment.md` | Requirement-to-evidence mapping | Markdown | Required |
| Python generator | `src/data_generation/generate_synthetic_data.py` | Deterministic synthetic data | Python | Code included above |
| Python validation | `src/validation/validate_data.py` | Quality checks | Python | Required |
| SQL scripts | `sql/*.sql` | BigQuery ingestion/transformation/analysis | SQL | Plan and core code above |
| Colab notebooks | `notebooks/*.ipynb` | Generation, validation, analysis | Colab | Required |
| CSV files | `data/synthetic/*.csv` | Generated raw inputs | Python | Generated after execution; do not invent now |
| Analytical tables | `driiiportfolio.snap_growth_analytics.*` | User metrics and results | BigQuery SQL | Created after execution |
| Dashboard views | `driiiportfolio.snap_growth_dashboard.*` | Looker Studio sources | BigQuery SQL | Created after execution |
| Figures | `outputs/figures/` | Executed plots | Python | Generated after execution |
| Reports | `outputs/reports/` | DQ and statistical reports | Python/Markdown | Generated after execution |
| Looker Studio report | External report URL | Executive dashboard | Looker Studio | Build after views exist |

## Sources and verification notes

- Snap careers/job description: `https://careers.snap.com/jobs` and the source job-description file in this repository.
- Snap SEC filings: `https://investor.snap.com/financials/sec-filings/default.aspx` and `https://www.sec.gov/edgar/browse/?CIK=0001564408`.
- BigQuery datasets: `https://docs.cloud.google.com/bigquery/docs/datasets`.
- BigQuery CSV loading: `https://docs.cloud.google.com/bigquery/docs/loading-data-cloud-storage-csv`.
- BigQuery cost controls: `https://docs.cloud.google.com/bigquery/docs/best-practices-costs`.
- BigQuery quotas: `https://cloud.google.com/bigquery/quotas`.
- BigQuery pricing: `https://cloud.google.com/bigquery/pricing`.
- Google Colab FAQ: `https://research.google.com/colaboratory/faq.html`.
- Looker/BigQuery documentation: `https://docs.cloud.google.com/looker/docs/db-config-google-bigquery`.

Changing cloud prices, quotas, connector behavior, and runtime policies are **UNKNOWN — REQUIRES VALIDATION** at the time of execution.

# End-to-End Processing Manual
## Synthetic Snapchat Growth Experiment Analytics

**Repository:** `DRIII33/snap-data-science-lv4-`  
**Primary blueprint:** [`docs/portfolio_project_blueprint.md`](./portfolio_project_blueprint.md)  
**BigQuery project:** `driiiportfolio`  
**Dashboard:** `Synthetic Snapchat Growth Experiment — Executive Decision Support`  
**Last reviewed:** 2026-09-24

---

## 1. Purpose and Operating Rules

This manual converts the portfolio blueprint into an executable process. Follow it from business framing through data generation, BigQuery, statistical analysis, Looker Studio, documentation, and final quality assurance.

This is a **portfolio simulation**. It is not an official Snap Inc. project and does not use confidential Snap data. Every generated record is **SYNTHETIC DATA**. Any simulated treatment effect is a data-generating assumption, not an observed Snap result.

Use these labels throughout the project:

- **VERIFIED FACT:** Directly documented by the job description or an official technical source.
- **ASSUMPTION:** A deliberate project-design choice that is not known to be true of Snap.
- **SYNTHETIC DATA:** Generated portfolio records.
- **EXECUTION-DEPENDENT RESULT — MUST BE GENERATED AFTER RUNNING THE PROVIDED CODE:** Any count, p-value, confidence interval, effect size, chart result, or recommendation that depends on execution.
- **INTERPRETATION:** An inference from executed evidence, not a directly observed fact.
- **UNKNOWN — REQUIRES VALIDATION:** Information that cannot be established from the repository or authoritative documentation.

Do not publish numerical findings before executing the notebooks and validating the output.

---

## 2. Required Software and Access

### 2.1 Accounts and permissions

You need:

1. A GitHub account with write access to `DRIII33/snap-data-science-lv4-`.
2. A Google account for Google Colab and Looker Studio.
3. Access to Google Cloud project `driiiportfolio`, or permission to use another project if the specified project is unavailable.
4. BigQuery permissions sufficient to create datasets and tables, run queries, and connect Looker Studio.

If the project or permissions are unavailable, record **UNKNOWN — REQUIRES VALIDATION** in the run log rather than assuming access.

### 2.2 Local Python environment

The project can be run in Colab. A local environment is optional. Use Python 3.x and install:

```bash
pip install numpy pandas scipy statsmodels matplotlib seaborn pyarrow google-cloud-bigquery
```

Pin versions only after testing them. Record the actual versions in `outputs/reports/run_metadata.json`.

### 2.3 Source documentation

Verify changing product terms before execution using official documentation:

- [BigQuery datasets](https://docs.cloud.google.com/bigquery/docs/datasets)
- [BigQuery CSV loading](https://docs.cloud.google.com/bigquery/docs/loading-data-cloud-storage-csv)
- [BigQuery cost controls](https://docs.cloud.google.com/bigquery/docs/best-practices-costs)
- [BigQuery pricing](https://cloud.google.com/bigquery/pricing)
- [BigQuery quotas](https://cloud.google.com/bigquery/quotas)
- [Google Colab FAQ](https://research.google.com/colaboratory/faq.html)
- [Looker Studio documentation](https://docs.cloud.google.com/data-studio)
- [Looker Studio quick start](https://docs.cloud.google.com/data-studio/quick-start-guide)

Prices, quotas, free-tier terms, connector behavior, and runtime availability are changeable. Do not hard-code them into the project as permanent facts.

---

## 3. Repository Preparation

### Step 1 — Review the source materials

1. Open `docs/job_description.md`.
2. Open `docs/portfolio_project_blueprint.md`.
3. Confirm that the project remains a hypothetical Snapchat growth experiment.
4. Confirm that no Snap-internal data, systems, or results are claimed.
5. Create a working branch if your repository workflow requires one.

### Step 2 — Create the implementation structure

Use the structure specified by the blueprint:

```text
README.md
Executive_Summary.md
Dashboard_Executive_Summary.md
Project_Disclaimer.md
requirements.txt
docs/
sql/
notebooks/
src/data_generation/generate_synthetic_data.py
src/validation/validate_data.py
src/analysis/experiment_analysis.py
data/synthetic/
dashboards/
outputs/figures/
outputs/reports/
tests/
```

Do not add empty files merely to fill a tree. Every committed file must have a defined purpose.

### Step 3 — Establish a run log

Create `outputs/reports/run_metadata.json` after the first run. Record:

- Git commit SHA
- Execution timestamp and timezone
- Python version
- Package versions
- Random seed
- User/event configuration
- BigQuery project and dataset locations
- Query job IDs if available
- Dashboard data-refresh timestamp
- Validation status

Never include credentials or service-account keys in the repository.

---

## 4. Business Framing Before Coding

Complete this work before generating data.

### 4.1 Write the decision statement

Use this exact decision framing:

> Should the hypothetical onboarding and feature-discovery treatment be expanded, iterated, or stopped based on its effect on day-28 retention, activation, subscription conversion, and guardrail metrics?

### 4.2 Define the primary estimand

The primary estimand is the intention-to-treat difference in day-28 retention:

```text
Risk difference = retention_rate(treatment) - retention_rate(control)
```

Define the unit as one eligible randomized user. Do not use events as the denominator for user-level outcomes.

### 4.3 Freeze hypotheses before looking at results

Document:

- Primary metric: D28 retention.
- Secondary metrics: D7 activation and D28 subscription conversion.
- Guardrails: notification opt-out, report events, and other explicitly defined experience proxies.
- Two-sided alpha: 0.05, unless a different value is justified and documented.
- Practical thresholds: project assumptions, not Snap standards.
- Segment analyses: exploratory unless separately powered and pre-specified.

Commit the hypothesis document before running the final analysis. This prevents post-hoc metric selection.

---

## 5. Generate the Synthetic Data

### Step 1 — Open Colab

1. Open a new Google Colab notebook.
2. Select a standard CPU runtime; GPU is not required.
3. Clone or download the repository, or upload the generator file.
4. Run the dependency installation cell.
5. Set the random seed and configuration variables.

### Step 2 — Run the generator

Run `src/data_generation/generate_synthetic_data.py`, or copy its code into the generation notebook. The default configuration should create:

- `users.csv`
- `experiment_assignments.csv`
- `events.csv`
- `subscriptions.csv`

The generator must:

1. Use a deterministic seed.
2. Preserve primary and foreign keys.
3. Create treatment and control groups.
4. Create fixed observation windows.
5. Generate events with timestamps and event types.
6. Generate subscription records separately from event records.
7. Save all files under `data/synthetic/`.
8. Print row counts and null summaries.
9. Run uniqueness, range, category, timestamp, and referential-integrity assertions.

### Step 3 — Record generated-data metadata

Record actual:

- Number of users
- Number of assignments
- Number of events
- Number of subscriptions
- File sizes
- Date ranges
- Treatment/control counts
- Seed
- Runtime
- Memory observations if available

These are **EXECUTION-DEPENDENT RESULT — MUST BE GENERATED AFTER RUNNING THE PROVIDED CODE**.

### Step 4 — Inspect the generated files

For every CSV:

```python
import pandas as pd
from pathlib import Path

for path in Path("data/synthetic").glob("*.csv"):
    df = pd.read_csv(path)
    print(path.name, df.shape)
    display(df.head())
    display(df.isna().sum())
```

Check that IDs are strings, dates/timestamps parse correctly, categories match the data dictionary, and no generated file contains credentials or real personal data.

---

## 6. Run Local Data Validation

Run `src/validation/validate_data.py` or the validation notebook.

### 6.1 Required checks

The validation report must contain these columns:

| Check | Expected result | Actual result | Status | Remediation |
|---|---|---|---|---|
| User primary-key uniqueness | Zero duplicates | Execution-dependent | PASS/FAIL | Remove or investigate duplicates |
| Assignment uniqueness | One assignment per user | Execution-dependent | PASS/FAIL | Investigate reassignment |
| Event primary-key uniqueness | Zero duplicate event IDs | Execution-dependent | PASS/FAIL | Deduplicate or quarantine |
| User foreign keys | Every event user exists | Execution-dependent | PASS/FAIL | Quarantine orphan events |
| Treatment categories | Only control/treatment | Execution-dependent | PASS/FAIL | Standardize or reject |
| Event categories | Approved event names | Execution-dependent | PASS/FAIL | Reject unexpected values |
| Timestamp validity | Non-null and within study bounds | Execution-dependent | PASS/FAIL | Quarantine invalid rows |
| Subscription keys | Existing users only | Execution-dependent | PASS/FAIL | Reject orphan subscriptions |
| Missingness | Required fields complete | Execution-dependent | PASS/FAIL | Document and remediate |
| Outliers | Investigated, not silently deleted | Execution-dependent | INVESTIGATE | Explain treatment |
| Leakage | No post-treatment adjustment variables | Zero violations | PASS/FAIL | Remove leaked features |

### 6.2 Defect testing

To demonstrate that tests work, make a temporary copy and inject one defect at a time:

- Duplicate an event ID.
- Replace a treatment value with `unknown`.
- Add an orphan user ID.
- Add an impossible timestamp.
- Add a negative count if counts are present.

The validator must fail the relevant check. Do not commit intentionally corrupted production inputs.

### 6.3 Validation exit criteria

Do not load data into BigQuery until:

- Required-key checks pass.
- Category checks pass.
- Foreign-key checks pass.
- Date checks pass.
- Any intentional test defects are removed.
- The report is saved under `outputs/reports/data_quality_report.csv`.

---

## 7. Create BigQuery Resources

### Step 1 — Select the project and location

Use project `driiiportfolio`. Select one BigQuery location and use it consistently for all datasets and connected resources. Dataset location mismatches can prevent queries or dashboard connections.

### Step 2 — Create datasets

Run `sql/01_create_datasets.sql` in the BigQuery SQL editor. Verify that these datasets exist:

```text
snap_growth_raw
snap_growth_transform
snap_growth_analytics
snap_growth_dashboard
```

If the SQL location is not accepted in your environment, create the datasets in the console and record the selected location in the run metadata.

### Step 3 — Create raw tables

Run `sql/02_create_raw_tables.sql` after editing the table definitions if necessary. Prefer explicit schemas. Confirm:

- `events` is partitioned by event date.
- Common filter/join fields are clustered where supported.
- Date, timestamp, boolean, integer, and string fields have deliberate types.
- Raw tables preserve source records; cleaning belongs in later layers.

### Step 4 — Load CSVs

Use either the BigQuery console or a documented `bq`/Python load process.

Console process:

1. Open BigQuery Explorer.
2. Select `driiiportfolio.snap_growth_raw`.
3. Select **Create table**.
4. Choose **Upload** or Cloud Storage as the source.
5. Select CSV format.
6. Specify the target table name.
7. Skip one leading header row.
8. Use the explicit schema from the data dictionary.
9. Confirm the correct partition configuration for events.
10. Create the table.

After every load, run:

```sql
SELECT COUNT(*) AS row_count FROM `driiiportfolio.snap_growth_raw.users`;
SELECT COUNT(*) AS row_count FROM `driiiportfolio.snap_growth_raw.experiment_assignments`;
SELECT COUNT(*) AS row_count FROM `driiiportfolio.snap_growth_raw.events`;
SELECT COUNT(*) AS row_count FROM `driiiportfolio.snap_growth_raw.subscriptions`;
```

Compare the results to the local CSV counts. A mismatch is a blocking issue until explained.

---

## 8. Run BigQuery Data Quality Checks

Run `sql/03_data_quality_checks.sql`.

Add checks for:

```sql
-- Required user columns
SELECT COUNT(*) AS failures
FROM `driiiportfolio.snap_growth_raw.users`
WHERE user_id IS NULL OR signup_date IS NULL;

-- One assignment per user
SELECT COUNT(*) AS duplicate_users
FROM (
  SELECT user_id
  FROM `driiiportfolio.snap_growth_raw.experiment_assignments`
  GROUP BY user_id
  HAVING COUNT(*) != 1
);

-- Orphan subscriptions
SELECT COUNT(*) AS orphan_subscriptions
FROM `driiiportfolio.snap_growth_raw.subscriptions` s
LEFT JOIN `driiiportfolio.snap_growth_raw.users` u USING (user_id)
WHERE u.user_id IS NULL;

-- Date validity
SELECT COUNT(*) AS invalid_dates
FROM `driiiportfolio.snap_growth_raw.events`
WHERE event_ts IS NULL OR DATE(event_ts) < DATE '2026-01-01';
```

Save query results, screenshots, or exported tables as validation artifacts. Do not only state that checks passed.

---

## 9. Transform and Standardize Data

Run `sql/04_transform.sql`.

The transformation layer must:

1. Normalize event names with `LOWER(TRIM(...))`.
2. Remove exact duplicate event records.
3. Reject null IDs and timestamps.
4. Retain an auditable relationship to raw data.
5. Create a clean event date for partition filtering.
6. Restrict event names to the documented event taxonomy.
7. Avoid silently converting invalid values into valid values.

Run a post-transform comparison:

```sql
SELECT COUNT(*) FROM `driiiportfolio.snap_growth_raw.events`;
SELECT COUNT(*) FROM `driiiportfolio.snap_growth_transform.clean_events`;
```

Explain every difference in the data-quality report.

---

## 10. Engineer User-Level Features

Run `sql/05_feature_engineering.sql`.

The output must have exactly one row per user. Validate that grain:

```sql
SELECT COUNT(*) AS rows, COUNT(DISTINCT user_id) AS users
FROM `driiiportfolio.snap_growth_analytics.user_experiment_metrics`;
```

These values must be equal. If they are not, investigate join multiplication before proceeding.

### Feature rules

- Pre-treatment variables: market, device type, acquisition channel, signup date, and any valid pre-treatment activity.
- Primary outcome: D28 retention.
- Secondary outcomes: D7 activation and D28 subscription conversion.
- Count outcomes: messages and app opens in fixed windows.
- Never use treatment-exposed events as pre-treatment adjustment variables.
- Do not use the simulated latent propensity in the final analysis; it exists only to create realistic synthetic relationships.
- Do not use hidden generator labels as observed analytical features.

Create a feature dictionary with definition, source, window, business meaning, and leakage risk.

---

## 11. Statistical Analysis in Colab

### Step 1 — Retrieve only the analytical dataset

Do not download raw event data into Colab for analysis if BigQuery has already aggregated it. Retrieve the one-row-per-user analytical table with only required columns.

### Step 2 — Verify assignment and grain

Run:

```python
assert df["user_id"].is_unique
assert set(df["treatment_group"].dropna()) <= {"control", "treatment"}
assert df["treatment_group"].notna().all()
```

Calculate treatment share and assess sample-ratio mismatch against the pre-specified assignment ratio.

### Step 3 — Run the primary analysis

For D28 retention:

1. Calculate user counts by treatment.
2. Calculate retention rates.
3. Calculate treatment minus control risk difference.
4. Calculate a 95% confidence interval.
5. Calculate a p-value using a suitable two-sample proportion method.
6. Report practical significance against the pre-specified threshold.
7. Keep the analysis intention-to-treat.

### Step 4 — Run secondary and guardrail analyses

Repeat the same structured process for activation, subscription conversion, and guardrails. Clearly label them secondary or exploratory.

### Step 5 — Run sensitivity analysis

Use a regression-adjusted model only with pre-treatment variables. Compare its estimate with the unadjusted ITT estimate. Explain any material difference.

### Step 6 — Check assumptions and diagnostics

Create outputs for:

- Treatment balance.
- Missingness.
- Outcome-window completeness.
- Distribution of count outcomes.
- Confidence intervals.
- Segment sample sizes.
- Multiple-testing treatment.
- Sensitivity to exclusions.
- Leakage audit.

### Step 7 — Export results

Save:

```text
outputs/reports/experiment_results.csv
outputs/reports/assumption_checks.csv
outputs/reports/analytical_validation_checklist.csv
outputs/figures/primary_effect.png
outputs/figures/retention_by_treatment.png
outputs/figures/segment_effects.png
```

Every numerical result is an **EXECUTION-DEPENDENT RESULT** until produced by the executed notebook.

---

## 12. Analytical Validation Checklist

Before writing findings, mark each item `PASS`, `FAIL`, or `INVESTIGATE`:

| Area | Check |
|---|---|
| Grain | One row per user in the analytical dataset |
| Keys | No duplicate user IDs or orphan foreign keys |
| Assignment | One assignment per user and valid treatment categories |
| SRM | Treatment allocation consistent with pre-specified design |
| Missingness | Required outcomes and assignment complete |
| Windows | Outcomes use fixed, non-overlapping, documented windows |
| Leakage | No post-treatment variable used as pre-treatment adjustment |
| Joins | No join explosion or duplicate counting |
| Statistics | Method matches binary/count outcome and randomized design |
| Uncertainty | Confidence intervals and effect sizes are included |
| Practicality | Statistical significance separated from business significance |
| Sensitivity | Alternative reasonable specifications evaluated |
| Reproducibility | Fresh runtime reproduces outputs using the same seed |
| Limitations | Synthetic-data and external-validity limits documented |

Any `FAIL` in grain, assignment, leakage, join logic, or outcome construction blocks publication.

---

# 13. Looker Studio Dashboard Build Manual

## 13.1 Dashboard identity and design system

**Report name:** `Synthetic Snapchat Growth Experiment — Executive Decision Support`

**Page names:**

1. `01 Executive Decision`
2. `02 Funnel and Retention`
3. `03 Segments and Guardrails`
4. `04 Data Quality and Methodology`

**Audience:** Hypothetical product, growth, analytics, engineering, and executive stakeholders.

**Design goals:** One decision per page, curated BigQuery views, explicit metric definitions, no raw-table joins inside charts, clear distinction between observed results and interpretation, and visible synthetic-data disclosure.

**Recommended visual style:**

- Canvas: 16:9 landscape.
- Background: white or very light gray.
- Header: dark charcoal/navy.
- Primary accent: Snap-inspired yellow used sparingly; this is a portfolio design choice and is not an official Snap brand asset.
- Positive: green only for favorable, validated direction.
- Negative/guardrail: red/orange.
- Neutral/unknown: gray.
- Use one consistent font and avoid decorative effects.
- Display rates as percentages with one decimal place unless small counts require more precision.
- Display counts with comma separators.
- Include a footer on every page: `Synthetic portfolio data | Not an official Snap Inc. report | Refresh: [timestamp]`.

## 13.2 Prepare BigQuery dashboard views

Connect Looker Studio to curated views in `driiiportfolio.snap_growth_dashboard`, not raw event tables.

Recommended views:

- `executive_summary`
- `funnel_summary`
- `retention_daily`
- `segment_results`
- `guardrail_results`
- `data_quality_summary`
- `experiment_metadata`

If a view does not yet exist, create it in `sql/07_dashboard_views.sql`. Prefer BigQuery views over Looker Studio blends because BigQuery provides centralized join logic, stable denominators, easier testing, and lower risk of inconsistent calculations.

### Suggested `executive_summary` fields

```text
metric_name STRING
metric_group STRING
treatment_group STRING
users INT64
metric_value FLOAT64
control_value FLOAT64
risk_difference FLOAT64
relative_difference FLOAT64
ci_lower FLOAT64
ci_upper FLOAT64
p_value FLOAT64
practical_threshold FLOAT64
result_status STRING
run_timestamp TIMESTAMP
```

### Suggested `funnel_summary` fields

```text
funnel_stage STRING
treatment_group STRING
users INT64
stage_rate FLOAT64
stage_order INT64
```

### Suggested `retention_daily` fields

```text
metric_date DATE
treatment_group STRING
users INT64
activated_users INT64
retained_users INT64
subscription_users INT64
activation_rate FLOAT64
d28_retention_rate FLOAT64
subscription_rate FLOAT64
```

### Suggested `segment_results` fields

```text
segment_name STRING
segment_value STRING
treatment_group STRING
users INT64
metric_name STRING
metric_value FLOAT64
risk_difference FLOAT64
ci_lower FLOAT64
ci_upper FLOAT64
sample_size_flag STRING
```

### Suggested `data_quality_summary` fields

```text
check_name STRING
check_group STRING
expected_result STRING
actual_result STRING
status STRING
remediation STRING
run_timestamp TIMESTAMP
```

## 13.3 Create the report and connect data

1. Sign in to Looker Studio.
2. Select **Create → Report**.
3. Name the report exactly `Synthetic Snapchat Growth Experiment — Executive Decision Support`.
4. Select the BigQuery connector.
5. Choose project `driiiportfolio`.
6. Choose the appropriate `snap_growth_dashboard` dataset.
7. Add each curated view as a data source only when required.
8. Confirm the field types: dates are Date, timestamps are Date & Time, rates are Percent/Number, IDs are Text, and counts are Number.
9. Rename confusing display labels in the data-source field configuration, but preserve source-field lineage in the documentation.
10. Set the report data credentials and sharing permissions deliberately. Do not make the report public if the connected data is not intended for public access.
11. Add the four pages and name them exactly as specified.

If the connector cannot see the project or dataset, verify Google Cloud permissions, dataset location, connector credentials, and that the authorized account is the intended account.

## 13.4 Add global controls

Add these controls to pages where they are meaningful:

- Date range control using `metric_date` or the documented study date.
- Drop-down filter for `market` when the underlying source contains market.
- Drop-down filter for `device_type` when available.
- Drop-down filter for `acquisition_channel` when available.
- Treatment-group selector only on diagnostic pages; the executive page should show control and treatment together.
- Reset/filter-clear affordance if supported.

Configure controls to affect the intended page or report. Avoid placing a control on a page when its field is absent or semantically incompatible with the source.

---

## PAGE TITLE: 01 Executive Decision

**Purpose:** Give leadership a decision-ready summary of the primary experiment result, secondary outcomes, guardrails, and analysis trustworthiness.

**Page-level controls:** Date range if applicable; market/device/channel filters only if the executive view was designed to support those dimensions. Default to all users.

### CHART 1: Eligible Users

**Chart Type:** Scorecard  
**Data Source:** `driiiportfolio.snap_growth_dashboard.executive_summary`  
**Dimensions:** None  
**Metrics:** `users`, aggregation `SUM`  
**Filter:** `metric_group = 'primary'` or use a dedicated one-row metric view.  
**Date Range Settings:** Use the report default study period; do not use an arbitrary rolling period.

**Calculated Field(s):** None if `users` is already a validated aggregate. If sourced from a one-row-per-user table, use a BigQuery view with `COUNT(DISTINCT user_id)` rather than a chart-level count.

**Visualization Notes:**

- Title: `Eligible Users`.
- Compact notation off if exact counts are important.
- Show comparison only if comparison semantics are meaningful.
- Add a subtitle or text note: `Synthetic randomized users in the analysis population`.

### CHART 2: Treatment Allocation

**Chart Type:** Scorecard  
**Data Source:** `executive_summary`  
**Dimensions:** None  
**Metrics:** `treatment_share`, aggregation `AVG` only if the view has one row; otherwise calculate in BigQuery.  
**Filter:** `metric_name = 'treatment_share'`.

**Calculated Field:** Prefer BigQuery. If required at chart level and the source contains aggregated fields:

```text
SUM(treatment_users) / SUM(users)
```

**Data type:** Percent. **Aggregation:** Aggregated.

**Visualization Notes:** Title `Treatment Allocation`; add a note with the expected assignment ratio. Do not label the allocation as balanced until the executed SRM check passes.

### CHART 3: Primary D28 Retention by Group

**Chart Type:** Bar chart, horizontal  
**Data Source:** `executive_summary`  
**Dimension:** `treatment_group`  
**Metric:** `metric_value`, aggregation `AVG` if one row per group/metric; preferably `SAFE_DIVIDE(SUM(retained_users), SUM(users))` in BigQuery.  
**Filter:** `metric_name = 'd28_retention'`.  
**Sort:** `treatment_group` ascending with control first.

**Calculated Field:** If using row-level counts, create in BigQuery:

```sql
SAFE_DIVIDE(SUM(retained_users), SUM(users)) AS retention_rate
```

Do not average precomputed percentages across unequal groups.

**Visualization Notes:**

- Title: `D28 Retention by Experiment Group`.
- Data labels on, one decimal place.
- Control color gray; treatment color yellow or blue.
- Add a reference line only for the control value if the chart supports a fixed/metric reference line; otherwise use the effect chart below.
- Enable cross-filtering only if clicking a group should filter the other page components.

### CHART 4: Primary Effect with Confidence Interval

**Chart Type:** Horizontal bar chart or table with metric and CI; use a table if the connector cannot render an interval cleanly.  
**Data Source:** `executive_summary`  
**Dimension:** `metric_name`  
**Metrics:** `risk_difference`, `ci_lower`, `ci_upper`, `p_value`; aggregation `AVG` only when one row exists per metric.  
**Filter:** `metric_name = 'd28_retention'`.

**Calculated Field:**

```text
CASE
  WHEN risk_difference >= practical_threshold THEN 'Positive practical signal'
  WHEN risk_difference <= -practical_threshold THEN 'Negative practical signal'
  ELSE 'Below practical threshold'
END
```

**Data type:** Text. **Aggregation:** Record-level.

**Visualization Notes:**

- Title: `Primary Effect: Treatment − Control`.
- Display the effect in percentage points, not only percent relative change.
- Show `ci_lower` and `ci_upper` in a table or tooltip.
- Add a zero reference line.
- Add a second reference line only if the practical threshold is documented.
- Use explicit text: `Causal interpretation applies only to the simulated randomized assignment; external validity is not established.`

### CHART 5: Outcome Scorecards Row

Create three scorecards:

1. `D7 Activation Rate` — metric `activation_rate`, filtered to `metric_name = 'activation'`.
2. `D28 Subscription Conversion` — metric `subscription_rate`, filtered to `metric_name = 'subscription_conversion'`.
3. `Guardrail Status` — metric or text from `guardrail_results`; use a table if a text scorecard is unsupported.

For each rate, use a BigQuery-calculated numerator/denominator rate. Do not average segment rates.

### CHART 6: Decision Status

**Chart Type:** Table with one row  
**Data Source:** `executive_summary`  
**Dimension:** `result_status`  
**Metrics:** `risk_difference`, `ci_lower`, `ci_upper`, `p_value`, `users`  
**Filter:** `metric_name = 'd28_retention'`.

**Calculated Field:** Do not make an irreversible launch recommendation in Looker Studio. Display a status generated by the statistical notebook, such as `EXECUTION-DEPENDENT RESULT` until populated.

**Visualization Notes:** Conditional formatting:

- Green only for a validated positive recommendation.
- Orange for investigate/iterate.
- Red for validated negative or guardrail-harm status.
- Gray for not run or insufficient data.

---

## PAGE TITLE: 02 Funnel and Retention

**Purpose:** Explain where user behavior differs across the onboarding and early product funnel.

**Page-level controls:** Date range, market, device, acquisition channel, treatment group.

### CHART 7: Onboarding Funnel

**Chart Type:** Funnel chart if available; otherwise horizontal bar chart with stage ordering.  
**Data Source:** `funnel_summary`  
**Dimension:** `funnel_stage`  
**Metric:** `users`, aggregation `SUM`  
**Sort:** `stage_order` ascending.  
**Filter:** Optional treatment group and page controls.

**Calculated Field:**

```text
SAFE_DIVIDE(SUM(users), SUM(eligible_users))
```

Use a BigQuery view if `eligible_users` is not at the same grain. Name the field `stage_rate` and format as Percent.

**Visualization Notes:**

- Title: `User Funnel by Experiment Stage`.
- Show absolute users and rate where the chart supports both.
- Do not use a pie chart for sequential funnel stages.
- Apply consistent treatment colors.
- Enable cross-filtering by treatment group or market if appropriate.

### CHART 8: Daily Activation Trend

**Chart Type:** Time series  
**Data Source:** `retention_daily`  
**Dimension:** `metric_date`  
**Metric:** `activation_rate`, aggregation `AVG` only if one row per date/group; otherwise calculate from counts.  
**Breakdown:** `treatment_group`  
**Date Range Dimension:** `metric_date`  
**Default Date Range:** Full synthetic study period.

**Calculated Field:** Prefer:

```sql
SAFE_DIVIDE(SUM(activated_users), SUM(users)) AS activation_rate
```

**Visualization Notes:**

- Title: `Activation Rate Over Time`.
- Lines: control and treatment.
- Points on only when the number of dates is manageable.
- Use a zero-to-one percent axis where possible.
- Add a trendline only as descriptive context; do not interpret it causally.
- Show missing dates explicitly or document why they are absent.

### CHART 9: D28 Retention Comparison

**Chart Type:** Grouped bar chart  
**Data Source:** `retention_daily` or a cohort view  
**Dimension:** cohort date or cohort week  
**Metric:** `d28_retention_rate`, aggregation based on validated numerator/denominator fields  
**Breakdown:** `treatment_group`  
**Sort:** cohort date ascending.

**Visualization Notes:**

- Title: `D28 Retention by Cohort and Group`.
- Use a consistent cohort window.
- Do not show incomplete cohorts as if they have complete D28 observation.
- Filter out cohorts without a full 28-day follow-up using a documented field.

### CHART 10: Engagement Distribution

**Chart Type:** Box plot if supported; otherwise table or histogram alternative.  
**Data Source:** `user_experiment_metrics`  
**Dimension:** `treatment_group`  
**Metrics:** `opens_28d`, `messages_28d`; aggregation `AVG`, `MEDIAN`, or percentile fields supplied by BigQuery/Python.  
**Filter:** Eligible users with complete windows.

**Visualization Notes:**

- Title: `Engagement Distribution — 28-Day Window`.
- Prefer median and percentile outputs for heavy-tailed counts.
- Do not use a mean-only scorecard to imply that a skewed distribution is symmetric.
- Add a methodology note that engagement counts are secondary outcomes.

### CHART 11: Retention Metric Table

**Chart Type:** Table  
**Data Source:** `executive_summary`  
**Dimensions:** `metric_name`, `treatment_group`  
**Metrics:** `users`, `metric_value`, `risk_difference`, `ci_lower`, `ci_upper`, `p_value`  
**Rows:** Limit to documented primary and secondary metrics.

**Visualization Notes:**

- Title: `Experiment Metric Detail`.
- Sort primary metric first using a BigQuery `metric_order` field.
- Format rates as percentages and p-values consistently.
- Add conditional formatting only to effect direction/status, not raw p-values alone.

---

## PAGE TITLE: 03 Segments and Guardrails

**Purpose:** Identify whether effects differ across pre-treatment segments and whether the treatment creates potential user-experience harm.

**Page-level controls:** Segment name, market, device type, acquisition channel, treatment group, date range where supported.

### CHART 12: Segment Effect Forest Table

**Chart Type:** Table; use a horizontal bar chart if an interval-capable chart is available.  
**Data Source:** `segment_results`  
**Dimensions:** `segment_name`, `segment_value`, `metric_name`  
**Metrics:** `users`, `risk_difference`, `ci_lower`, `ci_upper`, `p_value`, `sample_size_flag`  
**Filter:** `metric_name = 'd28_retention'`.

**Calculated Field:**

```text
CASE
  WHEN sample_size_flag != 'OK' THEN 'Small sample — investigate'
  WHEN ci_lower > 0 THEN 'Positive interval'
  WHEN ci_upper < 0 THEN 'Negative interval'
  ELSE 'Interval crosses zero'
END
```

**Visualization Notes:**

- Title: `D28 Retention Effect by Pre-Treatment Segment`.
- Sort by segment name and value, not by favorable effect unless explicitly selected.
- Display sample sizes beside effects.
- Do not claim subgroup causality when cells are underpowered.
- Include a note that segment findings are exploratory unless pre-specified and powered.

### CHART 13: Guardrail Rate Comparison

**Chart Type:** Grouped bar chart  
**Data Source:** `guardrail_results`  
**Dimension:** `guardrail_name`  
**Metric:** `metric_value`  
**Breakdown:** `treatment_group`  
**Filter:** only documented guardrails.

**Visualization Notes:**

- Title: `Guardrail Rates by Experiment Group`.
- Use neutral colors for control/treatment and warning colors only when a validated threshold is crossed.
- Add reference lines for pre-specified maximum acceptable rates.
- Do not infer user harm from a proxy without documenting its limitation.

### CHART 14: Guardrail Status Table

**Chart Type:** Table  
**Data Source:** `guardrail_results`  
**Dimensions:** `guardrail_name`, `result_status`  
**Metrics:** `risk_difference`, `ci_lower`, `ci_upper`, `p_value`, `users`.

**Calculated Field:**

```text
CASE
  WHEN risk_difference <= -guardrail_threshold THEN 'Potential harm — investigate'
  WHEN ABS(risk_difference) < guardrail_threshold THEN 'Within threshold'
  ELSE 'Potential change — investigate'
END
```

**Visualization Notes:**

- Title: `Guardrail Review`.
- Use conditional formatting on `result_status`.
- Include an explicit `Not evaluated` status.
- Do not automatically convert a statistical result into a safety conclusion.

### CHART 15: Segment Sample Sizes

**Chart Type:** Bar chart  
**Data Source:** `segment_results`  
**Dimension:** `segment_value`  
**Metric:** `users`, aggregation `SUM`  
**Breakdown:** `segment_name`.

**Visualization Notes:**

- Title: `Segment Sample Sizes`.
- Sort descending by users.
- Add a minimum sample-size reference line if documented.
- This chart exists to prevent overinterpreting unstable subgroup estimates.

---

## PAGE TITLE: 04 Data Quality and Methodology

**Purpose:** Make the analysis auditable and show stakeholders whether the dashboard is fit for decision support.

**Page-level controls:** Run timestamp, check group, status.

### CHART 16: Data-Quality Status Scorecard

**Chart Type:** Scorecard  
**Data Source:** `data_quality_summary`  
**Metric:** count of checks where `status = 'PASS'`; aggregation `COUNT` or a BigQuery-produced `passed_checks` value.  
**Filter:** latest `run_timestamp`.

**Calculated Field:** If using row-level checks:

```text
CASE WHEN status = 'PASS' THEN 1 ELSE 0 END
```

Use `SUM` as the aggregate. A BigQuery summary field is preferable.

**Visualization Notes:** Title `Passed Data-Quality Checks`; show a comparison with total checks only if both values are available.

### CHART 17: Data-Quality Check Table

**Chart Type:** Table  
**Data Source:** `data_quality_summary`  
**Dimensions:** `check_group`, `check_name`, `status`, `actual_result`  
**Metrics:** None or `failure_count`  
**Sort:** status severity, then check group.

**Visualization Notes:**

- Title: `Data-Quality Validation Results`.
- Apply red/orange/green conditional formatting to status.
- Show remediation text.
- Filter to latest run timestamp.

### CHART 18: Experiment Metadata Table

**Chart Type:** Table  
**Data Source:** `experiment_metadata`  
**Dimensions:** `metadata_key`, `metadata_value`  
**Metrics:** None.

Include:

- Experiment name
- Primary estimand
- Primary metric
- Study period
- Random seed
- Run timestamp
- Data version
- Synthetic-data disclosure
- Analysis status

### CHART 19: Methodology Scorecard/Notice

**Chart Type:** Text box, not a data chart.  
**Data Source:** None.  
**Content:**

```text
Primary analysis: intention-to-treat randomized comparison.
Primary outcome: day-28 retention.
Uncertainty: 95% confidence intervals.
Secondary outcomes and segments: exploratory unless otherwise documented.
Data: synthetic portfolio data; not Snap internal data.
Numerical findings: execution-dependent.
```

**Visualization Notes:** Use a shaded methodology card. Do not use a fake numeric score for methodological quality.

---

## 13.5 Calculated-field policy

Use BigQuery for any calculation that requires reliable denominators, joins, deduplication, or statistical output. Use Looker Studio calculated fields only for display logic, labels, simple ratios over already-compatible aggregates, and conditional formatting.

Avoid:

- Averaging percentages across unequal groups.
- Counting events where the metric requires users.
- Joining raw users and events in separate chart sources.
- Recomputing p-values or confidence intervals in Looker Studio.
- Hiding metric definitions inside undocumented chart formulas.
- Using a post-treatment field in a control or filter that is presented as pre-treatment.

## 13.6 Blended data policy

Default: **Do not blend data** for the core report. Use BigQuery views instead.

If a blend is unavoidable for a small display-only element:

- Source A: `executive_summary`, key `metric_name`, metrics `risk_difference`, `ci_lower`, `ci_upper`.
- Source B: `experiment_metadata`, key `metric_name` or a single constant key, metrics/fields for methodology context.
- Join: `LEFT JOIN` from Source A to Source B.
- Justification: preserve all experiment metrics even when metadata is incomplete.
- Validate row counts before and after the blend.

Do not blend two independently aggregated sources on a non-unique key. If the join key is not unique, create a BigQuery view with the correct grain.

## 13.7 BigQuery view alternative

If a chart needs a calculated metric, create it in BigQuery. Example:

```sql
CREATE OR REPLACE VIEW `driiiportfolio.snap_growth_dashboard.funnel_summary` AS
WITH stage_counts AS (
  SELECT
    treatment_group,
    COUNT(*) AS eligible_users,
    COUNTIF(activated) AS activated_users,
    COUNTIF(d28_retained) AS retained_users,
    COUNTIF(subscribed_28d) AS subscribed_users
  FROM `driiiportfolio.snap_growth_analytics.user_experiment_metrics`
  GROUP BY treatment_group
)
SELECT treatment_group, 'Eligible' AS funnel_stage, eligible_users AS users, 1 AS stage_order
FROM stage_counts
UNION ALL
SELECT treatment_group, 'Activated', activated_users, 2 FROM stage_counts
UNION ALL
SELECT treatment_group, 'D28 Retained', retained_users, 3 FROM stage_counts
UNION ALL
SELECT treatment_group, 'Subscribed', subscribed_users, 4 FROM stage_counts;
```

Connect the resulting view using **Add data → BigQuery → project → dataset → view**. Document the view SQL and grain in `docs/data_architecture.md`.

## 13.8 Dashboard sharing and refresh

1. Click **Share**.
2. Assign viewer/editor permissions deliberately.
3. Keep the report restricted unless public access is intentional.
4. Confirm that the data-source credentials are appropriate for viewers.
5. Document the refresh behavior and last successful run.
6. If scheduled delivery is used, verify the recipient list and report access.
7. Never send confidential credentials, raw data, or service-account keys through the dashboard.

## 13.9 Dashboard QA checklist

- [ ] Report name is exact.
- [ ] Page names are exact.
- [ ] Every chart uses the documented source view.
- [ ] Every chart has a title.
- [ ] Every metric has a definition and correct aggregation.
- [ ] User rates use user denominators, not event denominators.
- [ ] Date controls filter the intended charts.
- [ ] Treatment colors are consistent.
- [ ] Control is shown before treatment where applicable.
- [ ] Zero and practical-threshold reference lines are documented.
- [ ] Confidence intervals are not fabricated or recomputed incorrectly.
- [ ] Small segments are flagged.
- [ ] Data-quality page shows actual validation results.
- [ ] Synthetic-data disclaimer appears on every page or in a persistent footer.
- [ ] No raw table is connected directly unless explicitly justified.
- [ ] Dashboard totals reconcile to BigQuery query results.
- [ ] Filters do not cause denominator drift without a visible explanation.
- [ ] Report sharing and credentials are tested.
- [ ] Screenshot or PDF export matches the intended layout.

---

## 14. Document Findings and Recommendations

Only after the statistical notebook and dashboard are executed, write:

### Descriptive findings
What happened in the generated sample?

### Diagnostic findings
What mechanisms are plausible? Label these **INTERPRETATION**.

### Statistical findings
What are the executed estimates, confidence intervals, p-values, and effect sizes?

### Business findings
What decision follows, subject to assumptions and limitations?

### Recommendation format

| Evidence | Interpretation | Recommendation | Expected impact | Measurement plan | Risk/constraint |
|---|---|---|---|---|---|
| Executed result | Clearly labeled inference | Expand, iterate, or stop | Formula or qualitative only unless measured | Follow-up experiment/monitoring | Synthetic-data and external-validity limits |

Never invent revenue, user growth, or financial impact. If an estimate is useful, provide a formula and label every assumption.

---

## 15. Final End-to-End Run Order

1. Review job description and blueprint.
2. Freeze business decision, estimand, metrics, and thresholds.
3. Prepare repository and run metadata.
4. Run synthetic-data generator.
5. Run local validation.
6. Create BigQuery datasets.
7. Load raw CSV tables.
8. Reconcile BigQuery and local row counts.
9. Run BigQuery data-quality checks.
10. Transform and standardize events.
11. Engineer one-row-per-user analytical features.
12. Validate grain, keys, windows, and leakage.
13. Run statistical notebook.
14. Export results, figures, and validation reports.
15. Create or refresh dashboard views.
16. Build the Looker Studio report using this manual.
17. Reconcile dashboard values to SQL results.
18. Write findings and recommendations.
19. Complete README, executive summary, dashboard summary, disclaimer, and limitations.
20. Run final QA.
21. Reproduce the project from a fresh runtime.
22. Commit only reviewed artifacts and documentation.

---

## 16. Final Deliverable Manifest

| Deliverable | Location | Purpose | Generated by | Status |
|---|---|---|---|---|
| Processing manual | `docs/portfolio_project_process_manual.md` | End-to-end execution instructions | Markdown | This file |
| Blueprint | `docs/portfolio_project_blueprint.md` | Project architecture and rationale | Markdown | Existing |
| Synthetic generator | `src/data_generation/generate_synthetic_data.py` | Creates reproducible CSV inputs | Python | Required |
| Validation code | `src/validation/validate_data.py` | Local data-quality checks | Python | Required |
| Analysis code | `src/analysis/experiment_analysis.py` | Statistical analysis | Python | Required |
| Raw CSVs | `data/synthetic/*.csv` | Generated inputs | Python | Generated after execution |
| BigQuery datasets | `driiiportfolio.snap_growth_*` | Raw, transform, analytics, dashboard layers | BigQuery | Create during execution |
| BigQuery tables/views | `driiiportfolio.snap_growth_dashboard.*` | Curated dashboard sources | BigQuery SQL | Create during execution |
| Statistical outputs | `outputs/reports/` | Results, assumptions, validation | Colab/Python | Generated after execution |
| Figures | `outputs/figures/` | Dashboard/report visual evidence | Colab/Python | Generated after execution |
| Looker Studio report | External Looker Studio URL | Executive decision dashboard | Looker Studio | Build after views exist |
| Dashboard documentation | `dashboards/dashboard_specification.md` | Chart inventory and metric definitions | Markdown | Required |
| Executive materials | `Executive_Summary.md`, `Dashboard_Executive_Summary.md` | Stakeholder communication | Markdown | Complete after execution |
| Disclaimer | `Project_Disclaimer.md` | Non-affiliation and data disclosure | Markdown | Required |

**Completion criterion:** The project is complete only when a second person can follow this manual from a fresh environment, reproduce the synthetic inputs and analytical outputs, connect the curated BigQuery views to Looker Studio, and understand which findings are executed results versus assumptions or interpretations.
"""

from pathlib import Path
import numpy as np
import pandas as pd

SEED = 20260922
N_USERS = 50_000
START = pd.Timestamp("2026-01-01", tz="UTC")
OUT = Path("data/synthetic")
rng = np.random.default_rng(SEED)
OUT.mkdir(parents=True, exist_ok=True)

markets = np.array(["north_america", "europe", "rest_of_world"])
devices = np.array(["ios", "android", "web"])
channels = np.array(["organic", "paid_social", "referral", "search"])
users = pd.DataFrame({
    "user_id": [f"u_{i:07d}" for i in range(N_USERS)],
    "signup_date": (START + pd.to_timedelta(rng.integers(0, 60, N_USERS), unit="D")).date,
    "market": rng.choice(markets, N_USERS, p=[.35, .30, .35]),
    "device_type": rng.choice(devices, N_USERS, p=[.48, .48, .04]),
    "acquisition_channel": rng.choice(channels, N_USERS, p=[.55, .20, .15, .10]),
    "latent_propensity": np.clip(rng.normal(0, 1, N_USERS), -3, 3)
})

assign = pd.DataFrame({
    "user_id": users.user_id,
    "treatment_group": rng.choice(["control", "treatment"], N_USERS),
    "assignment_ts": pd.to_datetime(users.signup_date, utc=True) + pd.to_timedelta(rng.integers(0, 86_400, N_USERS), unit="s")
})

# SIMULATED DATA-GENERATING ASSUMPTION: treatment modestly increases activation.
base_activation = 1 / (1 + np.exp(-(0.2 + .55 * users.latent_propensity)))
treatment_lift = np.where(assign.treatment_group.eq("treatment"), 0.08, 0.0)
activated = rng.random(N_USERS) < np.clip(base_activation + treatment_lift, .01, .99)

n_events = int(N_USERS * 28)
user_idx = rng.integers(0, N_USERS, n_events)
events = pd.DataFrame({
    "event_id": [f"e_{i:09d}" for i in range(n_events)],
    "user_id": users.user_id.to_numpy()[user_idx],
    "event_ts": START + pd.to_timedelta(rng.integers(0, 90 * 86_400, n_events), unit="s"),
    "event_name": rng.choice(["app_open", "message_sent", "story_view", "lens_used", "feature_discovered"], n_events, p=[.40, .18, .22, .12, .08]),
    "session_id": [f"s_{i:010d}" for i in range(n_events)]
})

# Ensure activated users have at least one discovery event; this is simulated product logic.
activated_ids = users.loc[activated, "user_id"].to_numpy()
extra = pd.DataFrame({
    "event_id": [f"e_extra_{i:08d}" for i in range(len(activated_ids))],
    "user_id": activated_ids,
    "event_ts": START + pd.to_timedelta(rng.integers(0, 7 * 86_400, len(activated_ids)), unit="s"),
    "event_name": "feature_discovered",
    "session_id": [f"s_extra_{i:08d}" for i in range(len(activated_ids))]
})
events = pd.concat([events, extra], ignore_index=True)

# Retention is simulated from activation and latent propensity, not calculated from post-treatment events.
user_frame = users.merge(assign, on="user_id")
retention_p = 1 / (1 + np.exp(-(-1.0 + .9 * user_frame.latent_propensity + .9 * activated + .10 * user_frame.treatment_group.eq("treatment"))))
retained = rng.random(N_USERS) < retention_p
subscription_p = 1 / (1 + np.exp(-(-3.2 + .5 * user_frame.latent_propensity + .25 * activated + .08 * user_frame.treatment_group.eq("treatment"))))
subscriber = rng.random(N_USERS) < subscription_p
subscriptions = user_frame.loc[subscriber, ["user_id"]].copy()
subscriptions["subscription_date"] = pd.to_datetime(user_frame.loc[subscriber, "signup_date"], utc=True) + pd.to_timedelta(rng.integers(1, 29, len(subscriptions)), unit="D")
subscriptions["plan"] = rng.choice(["plus", "lens_plus"], len(subscriptions), p=[.75, .25])

# Persist latent labels only for validation/reproducibility; exclude from analytical features.
users["simulated_activation_label"] = activated
users["simulated_d28_retained_label"] = retained

for name, frame in [("users", users), ("experiment_assignments", assign), ("events", events), ("subscriptions", subscriptions)]:
    frame.to_csv(OUT / f"{name}.csv", index=False)

assert users.user_id.is_unique
assert assign.user_id.is_unique
assert events.event_id.is_unique
assert set(assign.user_id).issubset(set(users.user_id))
assert set(events.user_id).issubset(set(users.user_id))
assert set(subscriptions.user_id).issubset(set(users.user_id))
assert set(assign.treatment_group).issubset({"control", "treatment"})
assert events.event_ts.notna().all()
print({"users": len(users), "assignments": len(assign), "events": len(events), "subscriptions": len(subscriptions)})
print(users.isna().sum())

"""## Executive Review: GitHub Repository Deliverables Status

This document outlines the current status of required files and folders within the `snap-growth-experiment-analytics` GitHub repository, identifying those that still need to be generated or created. This assessment is based on the `portfolio_project_blueprint.md` and `portfolio_project_process_manual.md`.

---

### Top-Level Files (Yet to be created):

*   `README.md`: **Status: To create** (Public project orientation and reproduction instructions).
*   `Executive_Summary.md`: **Status: Template required** (C-suite narrative after execution).
*   `Dashboard_Executive_Summary.md`: **Status: Template required** (Dashboard use and interpretation).
*   `Project_Disclaimer.md`: **Status: Required** (Non-affiliation and synthetic-data disclosure).
*   `LICENSE`: **Status: Required** (Standard project license).
*   `.gitignore`: **Status: Required** (Configuration for Git to ignore specified files/folders).
*   `requirements.txt`: **Status: Required** (Pinning of Python package versions after testing).

### `docs/` Folder (Yet to be created):

*   `business_problem.md`: **Status: Required** (Scenario and analytical questions).
*   `data_dictionary.md`: **Status: Required** (Schemas, grains, keys, definitions).
*   `data_architecture.md`: **Status: Required** (BigQuery layers and lineage).
*   `data_flow.md`: **Status: Required** (End-to-end data flow).
*   `job_description_alignment.md`: **Status: Required** (Requirement-to-evidence mapping).
*   `statistical_methodology.md`: **Status: Required** (Estimands, tests, assumptions).
*   `stakeholder_operating_model.md`: **Status: Required** (Product-facing operating model).
*   `ai_use_protocol.md`: **Status: Required** (AI-tool use guidelines).
*   `limitations.md`: **Status: Required** (Documentation of project limitations).

### `data/` Folder:

*   `README.md`: **Status: Required** (Explanation of data folder contents).
*   `synthetic/` (folder): **Status: Folder required**, contents (`*.csv` files) to be generated after execution by the Python generator.

### `sql/` Folder (SQL files yet to be created from provided snippets):

*   `01_create_datasets.sql`: **Status: Required** (BigQuery dataset creation statements).
*   `02_create_raw_tables.sql`: **Status: Required** (BigQuery raw table creation with explicit schemas).
*   `03_data_quality_checks.sql`: **Status: Required** (BigQuery data quality checks).
*   `04_transform.sql`: **Status: Required** (BigQuery data transformation statements).
*   `05_feature_engineering.sql`: **Status: Required** (BigQuery user-level feature engineering).
*   `06_analysis_views.sql`: **Status: Required** (BigQuery analysis views).
*   `07_dashboard_views.sql`: **Status: Required** (BigQuery dashboard views).
*   `08_final_validation.sql`: **Status: Required** (BigQuery final validation checks).

### `notebooks/` Folder (Yet to be created):

*   `01_data_generation.ipynb`: **Status: Required** (Colab notebook for data generation).
*   `02_data_validation.ipynb`: **Status: Required** (Colab notebook for local data validation).
*   `03_statistical_analysis.ipynb`: **Status: Required** (Colab notebook for statistical analysis).

### `src/` Folder (Python source files):

*   `data_generation/generate_synthetic_data.py`: **Status: Content provided in a cell**, file needs to be saved to this location in the repository.
*   `validation/validate_data.py`: **Status: Required** (Python script for data quality checks).
*   `analysis/experiment_analysis.py`: **Status: Required** (Python script for statistical analysis).

### `dashboards/` Folder (Yet to be created):

*   `README.md`: **Status: Required** (Explanation of dashboard folder contents).
*   `dashboard_specification.md`: **Status: Required** (Chart inventory and metric definitions).

### `outputs/` Folder:

*   `figures/` (folder): **Status: Folder required**, figures to be generated after execution.
*   `reports/` (folder): **Status: Folder required**, reports to be generated after execution.

### `tests/` Folder (Yet to be created):

*   `data_quality_tests.md`: **Status: Required** (Documentation of data quality test cases).

---

**Note:** Several BigQuery resources (datasets, analytical tables, dashboard views) and the Looker Studio report are also pending creation/generation during the execution phase, as detailed in the blueprints.
"""